<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NativeWindows\IFCnative.NativeWindows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Msagl.WpfGraphControl" Version="1.2.1" />
  </ItemGroup>

</Project>
