import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  actions: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    overflow: "visible",
    zIndex: 105,
  },
  activeDocumentControl: {
    flex: 1,
    gap: 4,
    minWidth: 280,
  },
  appMeta: {
    color: "#64748b",
    fontSize: 10,
  },
  appTitle: {
    color: "#0f172a",
    fontSize: 16,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 11,
  },
  buttonPressed: {
    opacity: 0.7,
  },
  buttonPrimary: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  buttonPrimaryText: {
    color: "#ffffff",
  },
  buttonText: {
    color: "#18181b",
    fontSize: 12,
  },
  catalogFinding: {
    backgroundColor: "#ffffff",
    borderColor: "#dbe4ee",
    borderRadius: 7,
    borderWidth: 1,
    gap: 6,
    padding: 9,
  },
  catalogFindingStack: {
    gap: 8,
  },
  catalogItem: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    padding: 9,
  },
  catalogList: {
    gap: 6,
    maxHeight: 260,
  },
  codeBlock: {
    backgroundColor: "#f4f4f5",
    borderRadius: 6,
    color: "#18181b",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    padding: 10,
  },
  console: {
    flex: 1,
    gap: 8,
  },
  consoleLine: {
    color: "#e4e4e7",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    paddingVertical: 1,
  },
  consoleLines: {
    backgroundColor: "#09090b",
    borderRadius: 7,
    minHeight: 190,
    padding: 10,
  },
  collapsibleBody: {
    gap: 2,
    padding: 10,
  },
  collapsibleHeader: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  collapsibleHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  collapsibleMeta: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 1,
  },
  collapsibleSection: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    marginBottom: 8,
    overflow: "hidden",
  },
  collapsibleTitle: {
    color: "#18181b",
    fontSize: 12,
  },
  disabled: {
    opacity: 0.45,
  },
  diffEmpty: {
    alignItems: "flex-start",
    backgroundColor: "#f8fafc",
    borderColor: "#dbe4ee",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    padding: 14,
  },
  diffHeader: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  diffHeaderText: {
    flex: 1,
    minWidth: 220,
  },
  diffSummaryCard: {
    backgroundColor: "#f8fafc",
    borderColor: "#dbe4ee",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    minWidth: 240,
    padding: 10,
  },
  diffSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  diffSummaryText: {
    color: "#475569",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
  },
  diffSummaryTitle: {
    color: "#0f172a",
    fontSize: 11,
  },
  diffLine: {
    color: "#334155",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    paddingHorizontal: 8,
    paddingVertical: 1,
  },
  diffLineAdd: {
    backgroundColor: "#dcfce7",
    color: "#166534",
  },
  diffLineRemove: {
    backgroundColor: "#fee2e2",
    color: "#991b1b",
  },
  diffLines: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    minHeight: 190,
  },
  dropdownButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dropdownButtonText: {
    color: "#18181b",
    fontSize: 11,
  },
  dropdownCaret: {
    color: "#0f766e",
    fontSize: 11,
  },
  dropdownDetail: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 2,
  },
  dropdownFieldOverlay: {
    marginBottom: 0,
    position: "relative",
  },
  dropdownList: {
    maxHeight: 230,
  },
  dropdownMenu: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    marginTop: 5,
    overflow: "hidden",
  },
  dropdownMenuOverlay: {
    elevation: 16,
    left: 0,
    position: "absolute",
    right: 0,
    top: 63,
    zIndex: 120,
  },
  dropdownOption: {
    borderBottomColor: "#f4f4f5",
    borderBottomWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dropdownOptionActive: {
    backgroundColor: "#ccfbf1",
  },
  dropdownOptionDetail: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 2,
  },
  dropdownOptionText: {
    color: "#18181b",
    fontSize: 11,
  },
  dropdownOptionTextActive: {
    color: "#0f766e",
  },
  dropdownTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  editBlock: {
    backgroundColor: "#fafafa",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    gap: 8,
    marginBottom: 10,
    padding: 10,
  },
  empty: {
    color: "#71717a",
    fontSize: 12,
    paddingVertical: 8,
  },
  field: {
    gap: 5,
    marginBottom: 8,
  },
  fieldLabel: {
    color: "#71717a",
    fontSize: 11,
  },
  flexField: {
    flex: 1,
    minWidth: 82,
  },
  infoLabel: {
    color: "#71717a",
    fontSize: 11,
    width: 96,
  },
  infoRow: {
    flexDirection: "row",
    gap: 8,
  },
  infoSection: {
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    gap: 6,
    paddingBottom: 12,
    paddingTop: 4,
  },
  infoText: {
    color: "#18181b",
    flex: 1,
    fontSize: 11,
  },
  infoTitle: {
    color: "#18181b",
    fontSize: 13,
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    color: "#18181b",
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  monoInput: {
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
  },
  monoLine: {
    color: "#18181b",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 11,
    paddingVertical: 2,
  },
  panelScroll: {
    flex: 1,
    minHeight: 0,
  },
  psetAddRow: {
    backgroundColor: "#f8fafc",
    borderTopColor: "#cbd5e1",
    borderTopWidth: 1,
  },
  psetCellInput: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 0,
    borderWidth: 0,
    color: "#18181b",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    minHeight: 28,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  psetHeadCell: {
    backgroundColor: "#e2e8f0",
    color: "#334155",
    fontSize: 10,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  psetHeader: {
    alignItems: "center",
    backgroundColor: "#bfdbfe",
    borderBottomColor: "#93c5fd",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    minHeight: 34,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  psetHeaderMeta: {
    color: "#475569",
    fontSize: 10,
    marginTop: 1,
  },
  psetHeaderTitle: {
    color: "#0f172a",
    fontSize: 12,
  },
  psetHeaderInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "#0f172a",
    fontSize: 12,
    minHeight: 24,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  psetActionCell: {
    alignItems: "center",
    borderLeftColor: "#d4d4d8",
    borderLeftWidth: 1,
    justifyContent: "center",
    paddingHorizontal: 4,
    width: 86,
  },
  psetNameCell: {
    borderRightColor: "#d4d4d8",
    borderRightWidth: 1,
    flex: 1.25,
    minWidth: 0,
  },
  psetNameField: {
    flex: 1,
    minWidth: 180,
  },
  psetSection: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 7,
    borderWidth: 1,
    marginBottom: 10,
    overflow: "visible",
    position: "relative",
  },
  psetSourceField: {
    minWidth: 140,
  },
  psetTable: {
    alignSelf: "stretch",
    overflow: "visible",
    width: "100%",
  },
  psetTableEmptyRow: {
    backgroundColor: "#ffffff",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    paddingHorizontal: 8,
  },
  psetTableHead: {
    borderBottomColor: "#cbd5e1",
    borderBottomWidth: 1,
  },
  psetTableRow: {
    alignItems: "stretch",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 30,
    overflow: "visible",
  },
  psetToolbar: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 8,
    position: "relative",
    paddingHorizontal: 9,
    paddingVertical: 7,
    zIndex: 100,
  },
  psetToolbarControls: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    minWidth: 300,
  },
  psetToolbarSummary: {
    minWidth: 112,
  },
  psetToolbarInput: {
    flex: 1,
    fontSize: 11,
    minHeight: 34,
    minWidth: 0,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  psetMiniButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 5,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 26,
    paddingHorizontal: 8,
  },
  psetMiniButtonText: {
    color: "#18181b",
    fontSize: 10,
  },
  psetCatalogHint: {
    backgroundColor: "#f8fafc",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    flex: 1,
    minHeight: 34,
    minWidth: 180,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  psetCatalogHintMeta: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 1,
  },
  psetCatalogHintTitle: {
    color: "#18181b",
    fontSize: 11,
  },
  psetPrimaryButton: {
    alignItems: "center",
    backgroundColor: "#0f766e",
    borderRadius: 7,
    justifyContent: "center",
    minHeight: 34,
    paddingHorizontal: 14,
  },
  psetPrimaryButtonText: {
    color: "#ffffff",
    fontSize: 12,
  },
  psetTypeCell: {
    borderRightColor: "#d4d4d8",
    borderRightWidth: 1,
    flex: 0.72,
    minWidth: 0,
  },
  psetValueCell: {
    flex: 1.35,
    minWidth: 0,
    position: "relative",
  },
  psetValueCellOpen: {
    zIndex: 80,
  },
  psetValueInput: {
    flex: 1,
    minWidth: 0,
  },
  psetTypeMenu: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 6,
    borderWidth: 1,
    left: 4,
    overflow: "hidden",
    position: "absolute",
    right: 4,
    top: 30,
    zIndex: 90,
  },
  psetTypeMenuOption: {
    borderBottomColor: "#f4f4f5",
    borderBottomWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  safeArea: {
    backgroundColor: "#eef1f4",
    flex: 1,
  },
  segment: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderBottomColor: "#d4d4d8",
    borderColor: "#d4d4d8",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 1,
    marginBottom: -1,
    minHeight: 34,
    justifyContent: "center",
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  segmentActive: {
    backgroundColor: "#ffffff",
    borderBottomColor: "#ffffff",
    borderTopColor: "#0f766e",
    borderTopWidth: 3,
    paddingTop: 5,
  },
  segmentPressed: {
    backgroundColor: "#eef2f7",
  },
  segmented: {
    borderBottomColor: "#d4d4d8",
    borderBottomWidth: 1,
    flexGrow: 0,
    flexShrink: 0,
    marginBottom: 2,
    maxHeight: 36,
  },
  segmentedContent: {
    alignItems: "flex-end",
    flexDirection: "row",
  },
  segmentText: {
    color: "#52525b",
    fontSize: 10,
    textTransform: "capitalize",
  },
  segmentTextActive: {
    color: "#0f766e",
  },
  separator: {
    backgroundColor: "#e4e4e7",
    height: 1,
    marginVertical: 12,
  },
  sectionTitle: {
    color: "#18181b",
    fontSize: 12,
    marginBottom: 8,
  },
  mosaicShell: {
    flex: 1,
    minHeight: 0,
    padding: 6,
    zIndex: 0,
  },
  tileContent: {
    flex: 1,
    gap: 10,
    minHeight: 0,
    padding: 10,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  topbar: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    elevation: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
    overflow: "visible",
    paddingHorizontal: 12,
    paddingVertical: 6,
    position: "relative",
    zIndex: 100,
  },
  toolbarBrand: {
    flexShrink: 0,
    gap: 1,
    minWidth: 104,
  },
  toolbarMain: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 14,
    minWidth: 360,
  },
  documentTab: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 7,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 10,
    width: 220,
  },
  documentTabActive: {
    backgroundColor: "#ccfbf1",
    borderColor: "#0f766e",
  },
  documentTabMeta: {
    color: "#64748b",
    fontSize: 10,
    marginTop: 2,
  },
  documentTabMetaActive: {
    color: "#0f766e",
  },
  documentTabPressed: {
    opacity: 0.75,
  },
  documentTabs: {
    flexGrow: 0,
    flexShrink: 1,
    maxHeight: 44,
  },
  documentTabsContent: {
    gap: 6,
  },
  documentTabTitle: {
    color: "#18181b",
    fontSize: 11,
  },
  documentTabTitleActive: {
    color: "#0f172a",
  },
  treeItem: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    marginBottom: 6,
    padding: 9,
  },
  treeItemSelected: {
    backgroundColor: "#ccfbf1",
    borderColor: "#0f766e",
  },
  treeMeta: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 3,
  },
  treeDeleteButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#fff1f2",
    borderColor: "#fecdd3",
    borderRadius: 6,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 28,
    minWidth: 34,
    paddingHorizontal: 8,
  },
  treeDeleteButtonText: {
    color: "#be123c",
    fontSize: 10,
    fontWeight: "700",
  },
  treeActionRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  treePrimaryAction: {
    flex: 1,
    minWidth: 0,
  },
  treeTitle: {
    color: "#18181b",
    flex: 1,
    fontSize: 12,
  },
  treeTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    minWidth: 0,
  },
  treeToggle: {
    color: "#0f766e",
    fontSize: 12,
    width: 12,
  },
  windowMenu: {
    overflow: "visible",
    position: "relative",
    zIndex: 102,
  },
  windowMenuButton: {
    minWidth: 104,
  },
  windowMenuEmpty: {
    color: "#71717a",
    fontSize: 11,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  windowMenuOption: {
    alignItems: "center",
    borderBottomColor: "#f4f4f5",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  windowMenuOptionMeta: {
    color: "#0f766e",
    fontSize: 10,
  },
  windowMenuOptionPressed: {
    backgroundColor: "#ccfbf1",
  },
  windowMenuOptionText: {
    color: "#18181b",
    flex: 1,
    fontSize: 11,
  },
  windowMenuPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    elevation: 12,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    top: 42,
    width: 230,
    zIndex: 103,
  },
  zeroState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
});
