import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  actions: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    overflow: "visible",
    zIndex: 101,
  },
  appTitle: {
    color: "#18181b",
    fontSize: 18,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  buttonPressed: {
    opacity: 0.7,
  },
  buttonPrimary: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  buttonPrimaryText: {
    color: "#ffffff",
  },
  buttonText: {
    color: "#18181b",
  },
  codeBlock: {
    backgroundColor: "#f4f4f5",
    borderRadius: 6,
    color: "#18181b",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    padding: 10,
  },
  console: {
    flex: 1,
    gap: 8,
  },
  consoleLine: {
    color: "#e4e4e7",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    paddingVertical: 1,
  },
  consoleLines: {
    backgroundColor: "#09090b",
    borderRadius: 7,
    minHeight: 190,
    padding: 10,
  },
  collapsibleBody: {
    gap: 2,
    padding: 10,
  },
  collapsibleHeader: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  collapsibleHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  collapsibleMeta: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 1,
  },
  collapsibleSection: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    marginBottom: 8,
    overflow: "hidden",
  },
  collapsibleTitle: {
    color: "#18181b",
    fontSize: 12,
  },
  disabled: {
    opacity: 0.45,
  },
  diffEmpty: {
    alignItems: "flex-start",
    backgroundColor: "#f8fafc",
    borderColor: "#dbe4ee",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    padding: 14,
  },
  diffHeader: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  diffHeaderText: {
    flex: 1,
    minWidth: 220,
  },
  diffSummaryCard: {
    backgroundColor: "#f8fafc",
    borderColor: "#dbe4ee",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    minWidth: 240,
    padding: 10,
  },
  diffSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  diffSummaryText: {
    color: "#475569",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
  },
  diffSummaryTitle: {
    color: "#0f172a",
    fontSize: 11,
  },
  diffLine: {
    color: "#334155",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
    paddingHorizontal: 8,
    paddingVertical: 1,
  },
  diffLineAdd: {
    backgroundColor: "#dcfce7",
    color: "#166534",
  },
  diffLineRemove: {
    backgroundColor: "#fee2e2",
    color: "#991b1b",
  },
  diffLines: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    minHeight: 190,
  },
  dropdownButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dropdownButtonText: {
    color: "#18181b",
    fontSize: 11,
  },
  dropdownCaret: {
    color: "#0f766e",
    fontSize: 11,
  },
  dropdownDetail: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 2,
  },
  dropdownList: {
    maxHeight: 230,
  },
  dropdownMenu: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    marginTop: 5,
    overflow: "hidden",
  },
  dropdownOption: {
    borderBottomColor: "#f4f4f5",
    borderBottomWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dropdownOptionActive: {
    backgroundColor: "#ccfbf1",
  },
  dropdownOptionDetail: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 2,
  },
  dropdownOptionText: {
    color: "#18181b",
    fontSize: 11,
  },
  dropdownOptionTextActive: {
    color: "#0f766e",
  },
  dropdownTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  editBlock: {
    backgroundColor: "#fafafa",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    gap: 8,
    marginBottom: 10,
    padding: 10,
  },
  empty: {
    color: "#71717a",
    fontSize: 12,
    paddingVertical: 8,
  },
  field: {
    gap: 5,
    marginBottom: 8,
  },
  fieldLabel: {
    color: "#71717a",
    fontSize: 11,
  },
  flexField: {
    flex: 1,
    minWidth: 82,
  },
  infoLabel: {
    color: "#71717a",
    fontSize: 11,
    width: 96,
  },
  infoRow: {
    flexDirection: "row",
    gap: 8,
  },
  infoSection: {
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    gap: 6,
    paddingBottom: 12,
    paddingTop: 4,
  },
  infoText: {
    color: "#18181b",
    flex: 1,
    fontSize: 11,
  },
  infoTitle: {
    color: "#18181b",
    fontSize: 13,
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    color: "#18181b",
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  monoInput: {
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 10,
  },
  monoLine: {
    color: "#18181b",
    fontFamily: Platform.select({ default: "monospace", ios: "Menlo" }),
    fontSize: 11,
    paddingVertical: 2,
  },
  panelScroll: {
    flex: 1,
    minHeight: 0,
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  safeArea: {
    backgroundColor: "#eef1f4",
    flex: 1,
  },
  segment: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderBottomColor: "#d4d4d8",
    borderColor: "#d4d4d8",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 1,
    marginBottom: -1,
    minHeight: 34,
    justifyContent: "center",
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  segmentActive: {
    backgroundColor: "#ffffff",
    borderBottomColor: "#ffffff",
    borderTopColor: "#0f766e",
    borderTopWidth: 3,
    paddingTop: 5,
  },
  segmentPressed: {
    backgroundColor: "#eef2f7",
  },
  segmented: {
    borderBottomColor: "#d4d4d8",
    borderBottomWidth: 1,
    flexGrow: 0,
    flexShrink: 0,
    marginBottom: 2,
    maxHeight: 36,
  },
  segmentedContent: {
    alignItems: "flex-end",
    flexDirection: "row",
  },
  segmentText: {
    color: "#52525b",
    fontSize: 10,
    textTransform: "capitalize",
  },
  segmentTextActive: {
    color: "#0f766e",
  },
  separator: {
    backgroundColor: "#e4e4e7",
    height: 1,
    marginVertical: 12,
  },
  sectionTitle: {
    color: "#18181b",
    fontSize: 12,
    marginBottom: 8,
  },
  mosaicShell: {
    flex: 1,
    minHeight: 0,
    padding: 6,
    zIndex: 0,
  },
  tileContent: {
    flex: 1,
    gap: 10,
    minHeight: 0,
    padding: 10,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  topbar: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    elevation: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
    overflow: "visible",
    paddingHorizontal: 14,
    paddingVertical: 8,
    position: "relative",
    zIndex: 100,
  },
  treeItem: {
    backgroundColor: "#ffffff",
    borderColor: "#e4e4e7",
    borderRadius: 7,
    borderWidth: 1,
    marginBottom: 6,
    padding: 9,
  },
  treeItemSelected: {
    backgroundColor: "#ccfbf1",
    borderColor: "#0f766e",
  },
  treeMeta: {
    color: "#71717a",
    fontSize: 10,
    marginTop: 3,
  },
  treeTitle: {
    color: "#18181b",
    flex: 1,
    fontSize: 12,
  },
  treeTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    minWidth: 0,
  },
  treeToggle: {
    color: "#0f766e",
    fontSize: 12,
    width: 12,
  },
  windowMenu: {
    overflow: "visible",
    position: "relative",
    zIndex: 102,
  },
  windowMenuButton: {
    minWidth: 104,
  },
  windowMenuEmpty: {
    color: "#71717a",
    fontSize: 11,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  windowMenuOption: {
    alignItems: "center",
    borderBottomColor: "#f4f4f5",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  windowMenuOptionMeta: {
    color: "#0f766e",
    fontSize: 10,
  },
  windowMenuOptionPressed: {
    backgroundColor: "#ccfbf1",
  },
  windowMenuOptionText: {
    color: "#18181b",
    flex: 1,
    fontSize: 11,
  },
  windowMenuPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 7,
    borderWidth: 1,
    elevation: 12,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    top: 42,
    width: 230,
    zIndex: 103,
  },
  zeroState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
});
