<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Dock.Avalonia" Version="11.3.11.4" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" Version="11.3.11.4" />
    <PackageReference Include="Dock.Model.Mvvm" Version="11.3.11.4" />
    <PackageReference Include="Xbim.Essentials" Version="6.0.587" />
    <PackageReference Include="Xbim.Geometry" Version="6.3.891-netcore" />
  </ItemGroup>

</Project>
