//! IFC schema knowledge (IFC2X3, IFC4, IFC4X3): entity inheritance, positional
//! attribute names/types, enumerations and defined types.
//!
//! The tables live in `schema/*.txt` (generated by `tools/gen_schema.py`) and
//! are parsed lazily on first use.

use rustc_hash::FxHashMap;
use std::sync::OnceLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum SchemaId {
    Ifc2x3,
    Ifc4,
    Ifc4x3,
}

impl SchemaId {
    pub fn from_header(label: &str) -> SchemaId {
        let up = label.trim().to_ascii_uppercase();
        if up.starts_with("IFC4X3") || up.starts_with("IFC4X2") || up.starts_with("IFC4X1") {
            SchemaId::Ifc4x3
        } else if up.starts_with("IFC4") {
            SchemaId::Ifc4
        } else if up.starts_with("IFC2X") {
            SchemaId::Ifc2x3
        } else {
            SchemaId::Ifc4
        }
    }

    pub fn header_label(self) -> &'static str {
        match self {
            SchemaId::Ifc2x3 => "IFC2X3",
            SchemaId::Ifc4 => "IFC4",
            SchemaId::Ifc4x3 => "IFC4X3_ADD2",
        }
    }

    pub fn display(self) -> &'static str {
        match self {
            SchemaId::Ifc2x3 => "IFC2X3",
            SchemaId::Ifc4 => "IFC4",
            SchemaId::Ifc4x3 => "IFC4X3",
        }
    }

    pub fn get(self) -> &'static Schema {
        static S2: OnceLock<Schema> = OnceLock::new();
        static S4: OnceLock<Schema> = OnceLock::new();
        static S43: OnceLock<Schema> = OnceLock::new();
        match self {
            SchemaId::Ifc2x3 => S2.get_or_init(|| Schema::parse(include_str!("schema/ifc2x3.txt"))),
            SchemaId::Ifc4 => S4.get_or_init(|| Schema::parse(include_str!("schema/ifc4.txt"))),
            SchemaId::Ifc4x3 => S43.get_or_init(|| Schema::parse(include_str!("schema/ifc4x3.txt"))),
        }
    }
}

#[derive(Debug, Clone)]
pub struct AttrDef {
    pub name: String,
    pub optional: bool,
    pub is_ref: bool,
    pub is_list: bool,
    /// Declared type (entity, select, defined type or enumeration name).
    pub ty: String,
}

#[derive(Debug, Clone)]
pub struct EntityDef {
    /// CamelCase name, e.g. `IfcWall`.
    pub name: String,
    pub upper: String,
    pub parent: Option<usize>,
    /// All positional attributes including inherited ones.
    pub attrs: Vec<AttrDef>,
    pub own_start: usize,
    pub children: Vec<usize>,
}

#[derive(Debug, Default)]
pub struct Schema {
    pub entities: Vec<EntityDef>,
    by_upper: FxHashMap<String, usize>,
    pub enums: FxHashMap<String, Vec<String>>,
    /// Defined type name (upper) -> primitive ("string", "number", "boolean", "logical", ...)
    pub defined: FxHashMap<String, String>,
    defined_camel: FxHashMap<String, String>,
}

impl Schema {
    fn parse(text: &str) -> Schema {
        let mut s = Schema::default();
        let mut pending_parent: Vec<(usize, String)> = Vec::new();
        let mut own: Vec<Vec<AttrDef>> = Vec::new();
        let mut cur: Option<usize> = None;
        for line in text.lines() {
            let mut it = line.split(' ');
            match it.next() {
                Some("T") => {
                    let name = it.next().unwrap_or_default();
                    let prim = it.next().unwrap_or_default();
                    s.defined.insert(name.to_ascii_uppercase(), prim.to_string());
                    s.defined_camel.insert(name.to_ascii_uppercase(), name.to_string());
                }
                Some("N") => {
                    let name = it.next().unwrap_or_default();
                    let vals: Vec<String> = it.map(|v| v.to_string()).collect();
                    s.enums.insert(name.to_ascii_uppercase(), vals);
                    s.defined_camel.insert(name.to_ascii_uppercase(), name.to_string());
                }
                Some("E") => {
                    let name = it.next().unwrap_or_default().to_string();
                    let parent = it.next().unwrap_or("-").to_string();
                    let n_own = it.next().unwrap_or("0");
                    // numeric defined types appear as attribute-less root "entities" in the source listing
                    if parent == "-" && n_own == "0" && is_numeric_type_name(&name) {
                        s.defined.insert(name.to_ascii_uppercase(), "number".to_string());
                        s.defined_camel.insert(name.to_ascii_uppercase(), name.clone());
                    }
                    let idx = s.entities.len();
                    let upper = name.to_ascii_uppercase();
                    s.by_upper.insert(upper.clone(), idx);
                    s.entities.push(EntityDef { name, upper, parent: None, attrs: vec![], own_start: 0, children: vec![] });
                    own.push(Vec::new());
                    if parent != "-" {
                        pending_parent.push((idx, parent));
                    }
                    cur = Some(idx);
                }
                Some("A") => {
                    let name = it.next().unwrap_or_default().to_string();
                    let flags = it.next().unwrap_or("-");
                    let ty = it.next().unwrap_or("?").to_string();
                    if let Some(c) = cur {
                        own[c].push(AttrDef {
                            name,
                            optional: flags.contains('o'),
                            is_ref: flags.contains('r'),
                            is_list: flags.contains('l'),
                            ty,
                        });
                    }
                }
                _ => {}
            }
        }
        for (idx, parent) in pending_parent {
            if let Some(&p) = s.by_upper.get(&parent.to_ascii_uppercase()) {
                s.entities[idx].parent = Some(p);
                s.entities[p].children.push(idx);
            }
        }
        // resolve full attribute lists (parents first via memoized recursion)
        let n = s.entities.len();
        let mut done = vec![false; n];
        fn resolve(i: usize, s: &mut Schema, own: &Vec<Vec<AttrDef>>, done: &mut Vec<bool>) {
            if done[i] {
                return;
            }
            let mut attrs = Vec::new();
            if let Some(p) = s.entities[i].parent {
                resolve(p, s, own, done);
                attrs.extend(s.entities[p].attrs.iter().cloned());
            }
            let own_start = attrs.len();
            attrs.extend(own[i].iter().cloned());
            s.entities[i].attrs = attrs;
            s.entities[i].own_start = own_start;
            done[i] = true;
        }
        for i in 0..n {
            resolve(i, &mut s, &own, &mut done);
        }
        s
    }

    pub fn entity(&self, upper_name: &str) -> Option<&EntityDef> {
        self.index_of(upper_name).map(|i| &self.entities[i])
    }

    pub fn index_of(&self, name: &str) -> Option<usize> {
        if let Some(&i) = self.by_upper.get(name) {
            return Some(i);
        }
        self.by_upper.get(&name.to_ascii_uppercase()).copied()
    }

    /// Whether `child` is `parent` or one of its subtypes (names in any case).
    pub fn is_subtype_of(&self, child: &str, parent: &str) -> bool {
        let (Some(c), Some(p)) = (self.index_of(child), self.index_of(parent)) else {
            return false;
        };
        self.is_subtype_idx(c, p)
    }

    pub fn is_subtype_idx(&self, mut c: usize, p: usize) -> bool {
        loop {
            if c == p {
                return true;
            }
            match self.entities[c].parent {
                Some(next) => c = next,
                None => return false,
            }
        }
    }

    /// CamelCase entity name for an upper case STEP keyword.
    pub fn camel<'a>(&'a self, upper: &'a str) -> &'a str {
        match self.index_of(upper) {
            Some(i) => &self.entities[i].name,
            None => upper,
        }
    }

    pub fn camel_type_name<'a>(&'a self, upper: &'a str) -> &'a str {
        if let Some(i) = self.index_of(upper) {
            return &self.entities[i].name;
        }
        match self.defined_camel.get(&upper.to_ascii_uppercase()) {
            Some(n) => n,
            None => upper,
        }
    }

    pub fn attr_names(&self, upper: &str) -> Vec<&str> {
        match self.entity(upper) {
            Some(e) => e.attrs.iter().map(|a| a.name.as_str()).collect(),
            None => vec![],
        }
    }

    pub fn attr_index(&self, upper: &str, attr: &str) -> Option<usize> {
        self.entity(upper)?.attrs.iter().position(|a| a.name.eq_ignore_ascii_case(attr))
    }

    pub fn enum_values(&self, name: &str) -> Option<&Vec<String>> {
        self.enums.get(&name.to_ascii_uppercase())
    }

    /// All (transitive) subtypes of `name` including itself, as indices.
    pub fn subtypes(&self, name: &str) -> Vec<usize> {
        let mut out = Vec::new();
        if let Some(i) = self.index_of(name) {
            let mut stack = vec![i];
            while let Some(c) = stack.pop() {
                out.push(c);
                stack.extend(self.entities[c].children.iter().copied());
            }
        }
        out
    }

    /// Primitive for a defined type such as IFCLABEL -> "string".
    pub fn primitive_of(&self, type_name: &str) -> Option<&str> {
        self.defined.get(&type_name.to_ascii_uppercase()).map(|s| s.as_str())
    }

    /// Names of all non-abstract-looking entity types that are subtypes of `root`.
    pub fn concrete_subtypes_named(&self, root: &str) -> Vec<String> {
        let mut v: Vec<String> = self.subtypes(root).into_iter().map(|i| self.entities[i].name.clone()).collect();
        v.sort();
        v
    }

    /// Value type names usable in property values (defined types), sorted.
    pub fn measure_types(&self) -> Vec<String> {
        let mut v: Vec<String> = self.defined_camel.iter().filter(|(k, _)| self.defined.contains_key(*k)).map(|(_, v)| v.clone()).collect();
        v.sort();
        v
    }
}

fn is_numeric_type_name(n: &str) -> bool {
    (n.ends_with("Measure") && n != "IfcDescriptiveMeasure")
        || n.ends_with("Number")
        || matches!(n, "IfcInteger" | "IfcReal" | "IfcPositiveInteger" | "IfcTimeStamp" | "IfcDimensionCount" | "IfcParameterValue" | "IfcSpecularExponent" | "IfcSpecularRoughness" | "IfcCardinalPointReference" | "IfcNumericMeasure")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn positional_attributes() {
        let s = SchemaId::Ifc4.get();
        assert_eq!(s.attr_names("IFCSIUNIT"), vec!["Dimensions", "UnitType", "Prefix", "Name"]);
        assert_eq!(s.attr_names("IFCWALL").len(), 9);
        assert_eq!(s.attr_names("IFCGEOMETRICREPRESENTATIONSUBCONTEXT").len(), 10);
        assert!(s.is_subtype_of("IFCWALLSTANDARDCASE", "IFCPRODUCT"));
        assert!(!s.is_subtype_of("IFCPROPERTYSET", "IFCPRODUCT"));
        assert!(s.enum_values("IfcWallTypeEnum").unwrap().contains(&"PARTITIONING".to_string()));
        let s2 = SchemaId::Ifc2x3.get();
        assert_eq!(s2.attr_names("IFCWALL").len(), 8);
        assert_eq!(s2.attr_names("IFCPROPERTYSINGLEVALUE"), vec!["Name", "Description", "NominalValue", "Unit"]);
        let s3 = SchemaId::Ifc4x3.get();
        assert!(s3.is_subtype_of("IFCWALL", "IFCBUILTELEMENT"));
    }
}
